apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
  namespace: testing
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: app
      owner: app
  managed:
    roles:
      - name: miniflux_user
        ensure: present
        login: true
        passwordSecret:
          name: pg-miniflux-user
