apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
  namespace: testing
spec:
  instances: 1
  storage:
    size: 1Gi
  plugins:
   - name: barman-cloud.cloudnative-pg.io
     enabled: true
     isWALArchiver: true
     parameters:
       barmanObjectName: barman-s3-store
  managed:
    roles:
      - name: miniflux_user
        connectionLimit: 2
        ensure: present
        inherit: true
        login: true
        passwordSecret:
          name: pg-miniflux-user
    roles:
      - name: forgejo_user
        connectionLimit: 10
        ensure: present
        inherit: true
        login: true
        passwordSecret:
          name: pg-forgejo-user

# for backup objects
#  method: plugin
#  pluginConfiguration:
#    name: barman-cloud.cloudnative-pg.io
