---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-forgejo-user
  namespace: testing
spec:
  encryptedData:
    password: AgCGCjLUvv4ofvF9OLylMZoiG2WmiKQ6W4JUbKQByR8pGJJM0bayJxBtjnsTwUVNYcGidNyt9z4sO+ZqV4vA+PU7kU+MNgB7XnoxPQNhP0N9Ktl90a2hYuIBxTPepeQiHfA7qgbaxG8kk2S3CpsoezPYQokFoJnTSvp/kDFJ5uXpg0boKLP2gxZ197GlCFTWsFDkZwfRYyG7EEuLDCzL7rEZf+klpXnekJNGvnYkoZvnRgV0wgK8JH1VEHEykq3mxrXCsqkiJ2pNV0DJjESL8pkkhyBNZfOMlXN3CA/xGGTkNVEsNDvYXz+OjXJHRAp03YiawjrE4abym6VplsSsjqsQg+5OOhY6Ehjmp6gyZKcxSxkgny1KMkyOrxKcnhyw4GxiJMwCs/ezpjvoysnFELMpWJEMuhCmsa9aVkM9pJ+tGVrtOAn642HffbKFjQy1NHLDaNCLf6svItm2fbrwZvz0xkDLLTD9QVmaOhvpNDopAIkHfIDWiQ8MaGo1mleEr30MFUlZtx81YfNierKDlbGAdn7zFytyDE1R7sI+nWWWOCjdqI3/FOWqfSzcrzp9cXlYE4z41OLbfusx/xZOJ3YoKjYCu+kRRArHHH2mJtajqb7Uy+O5gBfDUBeVG0Zxor/R9bJW7nGnGpimoF7lQZ2yGf0GWpblvPATfrVZPr9pRx+WNI/K51lBLtwHmhC6bXuufvMGTIsbXaGhU64By3fLn08Ubdsxj3Tm8Ah61cXPyl3VVLgr0qkk
    username: AgBVXfb9BVWfF0i5myOvwFCg6y2XX8TShZkKddgqR7Y5BFbbkbSt7HxOGurP5TJVO2iBqkbKxpig+hYqsc7OjadWMfIhE+MKmE4xJbFNf0Rc26Nxw35eJyJTdKdI/LYFnWKlbM4YPeybv6yAoBCnX65UUiJXFyhU1aaS0H0H8OalSzpV8ZKf7bD2Pq51zt0L/wkxsh/fsAQrN2ymlCFWZSGVN/x2/GZnRX2oP6lzx+pp6E7qt4TjHSmzWKvnqGKuvEYCTAIr1h5lffD0BmQcLCILx/N837cipK/3g8k6EXoHEJt+3no9x70zTAauDNE+4pHbeOk+2bFutk5/TytywV6a1aWoggVq8ow+RUkcj0amge9JDWDmsw6ehLl3r+l4VYLcNaUVcCSYgI/Wz1gHqTnc5+UO/ys5hHjMwK1SSEDXPEeldcVax4xeKaCTjf9XP2bqBOvbsMRvkXCDmqaWozJzZFqijX40oHFK71vITlg841lF6VVnz+A+8IgXQ71Wy7nlmF1EYvkENfEVRtqfNRgE7R8sNMCgu33IR4ENCmEkG/5d/TnP5a3ZyKRu5CY7KePD8K4xLh6r1SqgdK/5/5OKKa4fZCa2ziCNmDqMmqMZPglIxi3mSjMokuHhX2pmeWj3798DTsGAhR6aEH0CIErbQjjefXsKu4SoLDeUZYTNJJGlBAaqs24RyIlgx1aZJXEwTWjI2b+izKboD6c=
  template:
    metadata:
      name: pg-forgejo-user
      namespace: testing
    type: Opaque
