apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-barman-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  project: platform
  source:
    repoURL: ${GIT_REPO}
    targetRevision: main
    path: apps/platform/databases/barman-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true

