apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: sops-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../secrets/pg-miniflux-user.secret.sops.yaml

