apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
  namespace: testing
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: app
      owner: app
  managed:
    roles:
      - name: miniflux_user
        ensure: present
        login: true
        createrole: true
        createdb: true
        passwordSecret:
          name: pg-miniflux-user

