apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: testing
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:60qJpNFhwPDPk5NzAw==,iv:W0Lu7qwO103kvOHpf6t3NhG6YwXv8vpJF/cgwv0wB9w=,tag:6s5AeZ+JcfvXLG1Xzv3JOQ==,type:str]
    password: ENC[AES256_GCM,data:dtnR6CjRhVoGHU5kOv/NHCYeugkiynNVwq7KUux92fCrcS97i+uB+A==,iv:pp3xMy0qPYXlEQRg1Wxr/U/ZzfyEUQ9UpW/AyJU6Vu4=,tag:X7eT3BdigCOpl6IJcTDizA==,type:str]
sops:
    age:
        - recipient: age13fhlq80ummtu3erxsugpsy4ezsz7dz0kwqwqjwapfc6jjehccu7qzs3a5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWFJKelNQZ0ZMWCt3c0g4
            emRMeHlsc1EzeGZJeW12L1BiNEFOMkMwdWxvCkdYRFV4UkNTVTQ3VDNHaE4yQVY2
            OE1BVnA1Nkc1cUFjZVFxQWl2NjJTVjgKLS0tIFpPdjR1d3FjSlhwaHcxaDhCdzkv
            bXQ1WDB5UEs3VkNhdUduM1ZrT0JvOWsKvavjMpQIKAH12GJ0duBo28ntW3wgBZkW
            mwdsRyzNJtOGfZcCUS8ManYtswtQyDrle/Csh9chbiYotX7+ro6Mvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T03:31:40Z"
    mac: ENC[AES256_GCM,data:yR6+9OkqtjzztjgPMboGiVz6Q7Y7UywhDHQu1/0vrgjszRIPOVLeTdC5nl4xJ/poPqDWWGccG31Ic2dR9+AXDBFyCkYTOG5xJGtjNTTbbvTLodNVv4kMkGerpDwecOi2I8CiTDMJWlhJTwfodzbbqGQdbuSLBuIZhe5T+EyciGM=,iv:YzWaVn4Y6L0H6rhF8CmuYYM+C4ZGkeT+jt5LPiY8Bko=,tag:vLFffHqQhm0XSCDJ7BoBWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
