apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-forgejo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: testing
  source:
    repoURL: oci://code.forgejo.org/forgejo-helm/forgejo
    targetRevision: 15.0.3
    path: .
    helm:
      releaseName: forgejo
      valuesObject:
        # Pin Forgejo APP version (image tag) to major v10 (last patch is 10.0.3)
        image:
          tag: "10.0.3"

        persistence:
          enabled: true
          storageClass: local-path
          size: 5Gi

        gitea:
          admin:
            passwordMode: initialOnlyRequireReset

          config:
            database:
              DB_TYPE: postgres
              HOST: "pg-r.testing.svc.cluster.local:5432"
              NAME: "forgejo"
              USER: "forgejo_user"
              SSL_MODE: disable

          additionalConfigFromEnvs:
            - name: FORGEJO__DATABASE__PASSWD
              valueFrom:
                secretKeyRef:
                  name: pg-forgejo-user
                  key: password

  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
