apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: b2-store
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://YOUR_BUCKET/cnpg/app-db
    endpointURL: https://s3.YOUR_REGION.backblazeb2.com
    s3Credentials:
      accessKeyId:
        name: s3-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: s3-creds
        key: SECRET_ACCESS_KEY
    wal:
      compression: gzip

